### ISSUE TITLE
Feedback on Forms

### ISSUE THREAD

**Issue by seanhess** [jtdaugherty/brick#262] opened 2020-02-07 19:39 UTC
Great library! I'm geeking out building terminal UIs for a toy project and having loads of fun. 

It looks like the Forms module is a bit too black of a box. I can't seem to figure out how to do either of the following without abandoning it for pure text editors. 

1. How to put two fields side by side? "Name:  [ John ] [ Doe ]"

2. How to change the form state in an event? In my application I want the user to be able to hit a key to generate a random name. `formState` gives me the current state of the form, but doesn't allow me to set it. I can do `continue $ mkForm modifedState` but then it forgets the focus state. 

Thanks so much for your hard work! Let me know if there are simple ways to accomplish these, otherwise consider it feedback :)

**Comment by jtdaugherty** [comment] 2020-02-08 00:11
Thanks for asking!

> How to put two fields side by side? "Name: [ John ] [ Doe ]"

For this, I think your best bet is to use [setFormConcat](http://hackage.haskell.org/package/brick-0.51/docs/Brick-Forms.html#v:setFormConcat). Still, that's not great because it requires a brittle matching on the list contents to pull things out and build your own layout.

> How to change the form state in an event?

By design, this is not possible. The reason is that the form API is designed so that once a form is created, it manages and validates its input state and only gives it to you when you ask for the state as a whole. If you were able to manipulate a field's state, it could violate the field's validation state.

A general point, though: what you want to do is totally reasonable, and there absolutely will be use cases for which the built-in `Forms` module is just not the right solution. The design of the current forms stuff makes some trade-offs that will not always be the right ones. I made it to make basic form layout use cases very easy to support, but at the cost of fine-grained customization. If your needs are more specialized, then you'll need to consider implementing your own field rendering and input handling.

In the past, someone else asked about something related to this. I gave a more in-depth technical response to it [on that ticket](https://github.com/jtdaugherty/brick/issues/200).

**Comment by jtdaugherty** [comment] 2020-02-08 00:17
To give an example of the core issue, since it's worth calling out:

Let's say you have a form field for editing text. That field's original input is the text value, and its state becomes the *editor* for editing that text (i.e., the state is not the state as you think of it -- the text -- but a Brick editor instead). If you want to change the text, we need to build an editor from the text, but doing that would cause jarring UI issues like resetting the cursor position. Changing the state from your perspective means the fields need to be told how to deal with other state changes that could be a consequence of that.

**Comment by jtdaugherty** [comment] 2020-02-19 03:52
@seanhess - please let me know if there is more we could work out on this issue, or close it if you have gotten what you need. Thanks!

**Comment by jtdaugherty** [comment] 2020-03-09 03:33
@seanhess - can you please provide an update?

**Comment by jtdaugherty** [comment] 2020-04-24 04:19
@seanhess I'm going to close this due to inactivity. Please re-open if you need anything further!

**Closed by jtdaugherty** 2020-04-24 04:19 UTC
