### ISSUE TITLE
Question (Bug?) about withAttr behaviour

### ISSUE THREAD

**Issue by iyefrat** [jtdaugherty/brick#288] opened 2020-09-03 22:05 UTC
Hi!

First off, thank you so much for making this library. It's fantastically documented and beginner friendly in a way few are.

Secondly, it seems that the first attribute set on a widget is set cannot be changed later (without `forceAttr`). For example:
```
withAttr red $ withAttr green $ str "text"
```
is green, not red (this works if you want to change a different attribute from default, like having `withAttr bold $` in the beginning). Is this the intended behavior? If so, I haven't found it documented anywhere, and If it is undocumented, I'll send a PR to update the docs because I was confused by for a while.

I started looking into this because I'm trying to make a highlightable list, where you can highlight the element under cursor for later use. I can kind of do this by putting a `WithAttr` in the widget creator function (the first argument of `renderList`), but then the highlighted attribute overrides `listSelectedAttr`, so you can't when a highlighted entry is selected. Plugging in an `override listAttr listHighlightedAttr` only works if I change `listRenderWithIndex` to have `WithAtrr listAttr $ ...` instead of `WithDefAttr listAttr $ ...`.

The odd thing is that both of these work: 
```
overrideAttr green red $ withAttr green $ str "text"
overrideAttr green red $ withDefAttr green $ str "text"
```
but only the first of these works:
```
 withAttr green $ overrideAttr green red $ str "text"
 withDefAttr green $ overrideAttr green red $ str "text"
```
Is this also intended? If so, would it be possible to make the last option work as well? I can try writing a PR if you don't have the time.

**Comment by jtdaugherty** [comment] 2020-09-03 22:12
Thanks for your report! I have also run into some oddities with how those attribute management functions work, and I'll need to think carefully about what would make sense. As I read over this I realized I *never* use `withAttr`. I use `withDefAttr` instead. I think in the cases where I had tried `withAttr` I didn't get the behavior I was looking for and then never came back around to revisit it. I'll give it some thought, and your example will be helpful.

**Comment by jtdaugherty** [comment] 2020-09-03 22:12
(Well, I use `forceAttr` a lot, too.)

**Comment by iyefrat** [comment] 2020-09-03 23:12
If it helps, while trying to understand what was going on here, I made this self documenting demonstration:

![image](https://user-images.githubusercontent.com/19792685/92182108-8b995700-ee53-11ea-9c1d-bd9e4d72848b.png)


[source code here](https://github.com/iyefrat/attr)

**Comment by jtdaugherty** [comment] 2020-09-06 16:55
Thanks for the demo program and screenshot. Looking at it, I think it would help me if you could point out the cells in that screenshot where the behavior is not what you would expect. That will help me understand where there are documentation issues vs. implementation issues.

**Comment by iyefrat** [comment] 2020-09-08 08:09
Primarily, I would expect the last `withAttr` applied to override the attribute, and for the last `withDefAttr` applied to override the default attribute, with the default attribute acting like it currently does, meaning that the map is initiated with a default attribute for all aspects (usually defAttr), and that each subsequent `withDefAttr` changes some of them to something else.

In pratical terms, this means that the in first column (counting from left to right), the top widget acts as we expect, with `magentaUnderline` overriding the default atribute. However, the middle widget acts counter intuitively (in my opinion), as the first attribute applied (`red`) is not overwritten later.

In the second column, the top widget only gets the underline from `magentaUnderine`, but not the color (as I would expect it to). Probably because it only modifies the "default" parts of the default attributes, and not the other parts. The middle widget acts as we would expect, as we would expect `red` to only override the `Underline` part of `magentaUnderline`.

Both the third and fourth columns act as we expect, overriding the specific color but not other ones. Double overrides are not checked in this image, but there I would generally expect transitivity, as in `overrideAttr b c (overrideAttr a b) = overrideAttr a c` and also for the map to remember in some sense what was overwritten `overrideAttr a c (overrideAttr a b) = overrideAttr a c`, because in my mind at least, overriding just creates an arrow that points from the former attribute to the ladder.

With the fifth column, from the top, the first widget acts as we expect, with the `blue` part just overwriting the color bit of `magentaUnderline`, but I would expect the second widget to be purple, keeping in line with the general logic of (last `withAttr` applied counts). the third and fouth widgets are essentially the same as the top two, with the third being as expected and the fourth not.

In the sixth column,  the top widget does not act as we expect, as it is green and not blue (which should be the new default attribute left unmodified by the red override), the second one does act as we expect, as we have color to override the new default attribute. I would expect the third widget to be blue with an underline, as `withDefAttr` would only modify the default color and not the default style.

In the seventh column, I'd expect the top widget to be `magentaUnderline`, as this is the new semantic meaning of `green`. This is basically what the second widget does.

These are all a bunch of disparate examples of expectations, but I can believe they all fit with the following rules:

- When it comes to setting the default attribute with `withDefAttr`, or setting the attribute with `withAttr`, the last function applied should count. These functions should only update the parts of the attribute that exist in their first input (`magentaUnderline` etc in the example), leaving the rest untouched. If you want to set an attribute that cannot be later changed, use `forceAttr`. perhaps introduce a `forceDefAttr` that forces a specific default attribute.

- The interaction between the set attribute and the set default attribute should stay the same, with the default attribute just providing styling for everything left unpsecified by the attribute.

- `overrideAttr` should act as a namespace arrow, meaning that it modified the internal `attrMap` with the rule that an `override a b` means that whenever you use `a`, you just use `b` instead. This should work the same for both the attribute and default attribute, and if you override before or after you set the attribute with a `with(Def)Attr`. Notably, this arrow behaviour should be be able to be changed later at the source, which is essentially what the two rules `overrideAttr b c (overrideAttr a b) = overrideAttr a c` and `overrideAttr a c (overrideAttr a b) = overrideAttr a c` Imply. The reason I find this intuitive is the general abstraction of `AttrName` over `Attr`. The names point either directly to an `Attr`, or to an other `AttrName` that eventually points to an `Attr`. The `attrMap` has an internal idea of what e.g. `listAttr` is, and this idea should be able to be modified even if we haven't directly used `listAttr` in the widget yet.

- `forceAttr` just lock the attribute to be whatever the `AttrName` is agaisnt the known default attribute (which is what it does anyway), currently the behaviour is that the last `forceAttribute` counts, and I'm split on whether or not this is what I expect or not. Perhaps you could introduce a `lockAttribute` function that bars any further changes, covering all bases. Let it be noted that `forceAttr` currently respect `overrides`, and again this is probably fine, but should be documented.

This is all just my opinion, and I although it took a while to write, I don't think the core behavior algorithm I suggest/intuit here is that complicated to understand, as it essentially boils down to last `with(Def)Attr` counts, override provides arrows in the map lookup tables instead of erasing infomation (and these arrows should work no matter when introduced, because the map is it's own thing), and `forceAttr` should let us ignore furher `withAttr`'s.

I think the reason why you find yourself using `forceAttr` a lot is that currently it is the only way to change previously set attributes without `overrideAttr`, which requires you to know what you are changing from.

**Comment by iyefrat** [comment] 2020-09-09 18:32
After further though I'm not sure that the behavior I described here for `overrideAttribute` is really possible just because of the fact that `Map k a` can only send `k`'s to `a`, and not `k`'s to other `k`'s that go to `a`'s. I haven't really been able to to find a type that does this and of course you might disagree that this is desired behavior in the first place. Also, there are some uses to the current behavior of specifying attributes early and not having them change later, because that lets you go from the specific to the general if you have nested widgets, but I think that could be more straightforwardly achieved with something like a `lockAttribute blue` function that locks the color to blue but still lets you change the style later on or something.

**Comment by jtdaugherty** [comment] 2020-09-11 23:01
I'm finding at this point that I'm feeling overwhelmed by the amount of detail to consider, so I'll just go back to the original ticket issues that were reported:

> withAttr red $ withAttr green $ str "text"

* You mentioned that this was green, not red. That is the expected behavior because `withAttr` sets the active drawing attribute. `str` then uses `green` to generate its output, and by that point, the outer `withAttr red` will have no effect since the image made by `str` has already been generated.
* By contrast, `withDefAttr foo` does something *very* different: it says that when an attribute name is looked up in the attribute map, that attribute lookup result should be merged with (or fall back to) `foo`.
* And `forceAttr foo` does something else: it says that when attribute lookups occur, they always map to `foo` no matter what.
* Finally, `overrideAttr a b` makes attribute lookups for `a` just turn into lookups for `b`.

> The odd thing is that both of these work:
>
> overrideAttr green red $ withAttr green $ str "text"
> overrideAttr green red $ withDefAttr green $ str "text"

If by "work" you mean "are both red" then that would be what I'd expect.

> but only the first of these works:
>
> withAttr green $ overrideAttr green red $ str "text"
> withDefAttr green $ overrideAttr green red $ str "text"

What do you mean by "works" for these? I'd expect the first one to result in red text and I'd expect the second one to be green. The second one would be green because the default attribute does not have anything to do with what `overrideAttr` does. It is completely separate in the attribute map data structure.

**Comment by jtdaugherty** [comment] 2020-09-11 23:14
I'll also point out that the `withAttr` behavior above is documented.

**Comment by iyefrat** [comment] 2020-09-18 15:40
>I'm finding at this point that I'm feeling overwhelmed by the amount of detail to consider, so I'll just go back to the original ticket issues that were reported:

Yeah sorry I was trying to be thorough but probably got a bit carried away.

>What do you mean by "works" for these? I'd expect the first one to result in red text and I'd expect the second one to be green. The second one would be green because the default attribute does not have anything to do with what overrideAttr does. It is completely separate in the attribute map data structure.

I was expecting the second result to also be red, since I was intuiting `overrideAttr` as saying that everything that was previously named green will now have the attribute named red, and this understanding seems to work for `overrideAttr green red $ withDefAttr green $ str "text"`. If the default attribute is separate, why does this work? Does `withAttr` use the internal map of the widget it's acting upon to resolve the meaning of the `AttrName` `green`, but `withDefAttr` use a different map?

>I'll also point out that the withAttr behavior above is documented.

Do you mean the following sentence in the haddock for `withAttr`:
>Note that the widget may use further calls to withAttr to override this; if you really want to prevent that, use forceAttr.

If so, I misunderstood it when first reading it. When I read further calls, I was specifically thinking of more `withAttr`'s applied to the result, not other `withAttr`'s in the input. If this is what you mean, I can send a MR that clarifies this if you want.

**Comment by jtdaugherty** [comment] 2022-02-08 06:46
I just realized that this old ticket is still open. Since it has been quite a while and since there was so much to consider, I'm hesitant about trying to pick up where we left off. @iyefrat I wanted to mention that there have been some recent updates to the documentation for the various attribute functions (as well as the relevant User Guide content on attributes). I'm wondering if that is helpful to you, since you mentioned something about the docs in your last comment.

I'm going to close this, but @iyefrat, if you would like to continue hashing out attribute API issues, please open a new issue with a simple use case that we can use to discuss. Thank you!

**Closed by jtdaugherty** 2022-02-08 06:46 UTC
