### ISSUE TITLE
How to add background colour?

### ISSUE THREAD

**Issue by Boarders** [jtdaugherty/brick#350] opened 2021-11-22 02:47 UTC
I have an widget which is similar to the one found in this blog post: https://samtay.github.io/posts/introduction-to-brick
I would like to add a background colour outside of the border of the two boxes but am not sure how you do it and have failed with my multiple attempts? Is this something that brick offers and if so do you have any suggestions for how to go about it?

I am happy to share more details if this is very unclear.

**Comment by jtdaugherty** [comment] 2021-11-22 03:15
Hi, thanks for opening this. If I understand you right, it sounds like what you want is to set the background color of the whole window. (In other words, the "default background color.") If that's the case, then the solution is to set the default attribute in the `AttrMap` when you create it, e.g.,
```haskell
import Brick.Util (bg)
import Graphics.Vty (green)

myApp :: App s e n
myApp =
    App { appAttrMap = attrMap (bg green) [...], ... }
```

To put this in terms of the article you mentioned, instead of using `V.defAttr` as the base attribute for `theMap`, you'd use `bg green`. Let me know if that makes sense and is what you are looking for.

**Comment by jtdaugherty** [comment] 2021-11-22 03:20
Also, if this does what you want but has the unintended effect of also setting the background color of your bordered areas, that's because of [how attribute resolution works](https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#how-attributes-work). If, for example, you would specifically like the bordered areas to have a background of `white`, then you'll need to set up a new attribute in your attribute map with `white` as the background and then use that attribute with `withDefAttr` to wrap the bordered areas in your drawing function.

**Comment by Boarders** [comment] 2021-11-22 04:05
Thank you for the fast reply and the very pleasant library. It may be helpful for me to screenshot as I think I am doing something silly, I have this code (full code here: https://github.com/Boarders/task):
```haskell
edAttrMap :: AttrMap
edAttrMap =
  attrMap globalDefault
    [ ("title"   , titleCol    `on` backgroundCol)
    , ("subtitle", subtitleCol `on` backgroundCol)
    , ("text"    , textCol     `on` backgroundCol)
    , ("to-do-list", textCol   `on` backgroundCol)
    , ("highlighted", textCol  `on` highlightCol)
    , (borderAttr, textCol     `on` borderCol)
    ]
 globalDefault :: Attr
globalDefault = textCol `on` backgroundCol
```
If I set the `backgroundCol` to black then I get the following:
![image](https://user-images.githubusercontent.com/29600376/142799474-9f98f452-8add-4112-9467-e7e7303585ce.png)
What I would like is the area outside of the boxes to also be this same colour, do you know what I am doing wrong?

**Comment by jtdaugherty** [comment] 2021-11-22 05:00
What boxes are you referring to in "outside the boxes"? The borders around "22/11/2021", for example? Put another way, are you wanting everything to have a black background in the above screenshot?

Tip: you can *completely* remove all mentions of `textCol` and `backgroundCol` from your `attrMap` pairs list. That's because that's the default background you chose with `attrMap globalDefault`, so any other attributes fall back to the global default. Any overrides take precedence, such as `titleCol`. So a better, more flexible, less redundant attribute map would just be:
```haskell
edAttrMap :: AttrMap
edAttrMap =
  attrMap globalDefault
    [ ("title", fg titleCol)
    , ("subtitle", fg subtitleCol)
    , ("highlighted", bg highlightCol)
    , (borderAttr, bg borderCol)
    ]
globalDefault :: Attr
globalDefault = textCol `on` backgroundCol
```

**Comment by Boarders** [comment] 2021-11-22 05:03
Yes, I was wondering how you do that with regards to background colour! Thanks for the tip regarding the attribute map, at present I was still in the experimental phase of figuring out how to work with the library so my code is a bit of a mess.

**Comment by jtdaugherty** [comment] 2021-11-22 05:05
Another thought, from looking at your code:
```haskell
drawPrevTasks :: Bwd Task -> Widget WidgetId
drawPrevTasks = foldr (\t w -> drawTask t <=> w) emptyWidget

drawNextTasks :: [Task] -> Widget WidgetId
drawNextTasks = foldr (\t w -> drawTask t <=> w) emptyWidget
```
These will likely be more efficient to render if you can rewrite them as a single `vBox` call rather than a binary tree of `<=>`, e.g.:
```haskell
drawNextTasks :: [Task] -> Widget WidgetId
drawNextTasks = vBox . fmap drawTask
```

**Comment by jtdaugherty** [comment] 2021-11-22 05:06
(And yeah, that probably isn't correct with respect to the order you want them in, but I just wanted to provide some pseudocode to make the point.)

**Comment by jtdaugherty** [comment] 2021-11-22 05:07
The reason that approach will be cheaper to draw is because `vBox` has quite a bit of overhead. So you'll get slightly faster rendering times (which will matter for larger UIs) if you minimize your calls to `vBox` and `hBox`. They're the most common combinator in Brick UIs and it can be tempting to use them everywhere, but it can help to reduce box trees when you can.

**Comment by jtdaugherty** [comment] 2021-11-22 05:07
For a small application with not a lot on the screen, you'd probably never notice a difference, though.

**Comment by jtdaugherty** [comment] 2021-11-22 05:10
Another tip:
```haskell
type WidgetId = Text
```
In the long run, this type will be better off as an algebraic type with constructors for each UI element. That way, your event handler can pattern-match on `WidgetId` values and you can detect failures at compile time. With string literals used here instead, it can be all too easy to make a typo in something like your `"cursor"` literal so that when you check for which cursor to show elsewhere, you could fail to match due to the typo.

**Comment by jtdaugherty** [comment] 2021-11-22 05:11
Here's an example of a type used in this way (leading to `Widget Name` in this case):

https://github.com/matterhorn-chat/matterhorn/blob/master/src/Matterhorn/Types.hs#L836

**Comment by jtdaugherty** [comment] 2021-11-22 05:14
Another thing to note: your call to `visible` in your `draw` function on line 206 will have no effect since it is called on a part of the UI that is not drawn inside of a `viewport`.

**Comment by jtdaugherty** [comment] 2021-11-22 05:22
Anyway, I got carried away with tips, but let me know if you still have a background color issue that you want to fix. I'm not sure whether the `attrMap` code above would have changed your situation.

**Comment by jtdaugherty** [comment] 2021-11-22 05:28
Oh, I just had a thought - by "outside the boxes" do you mean "the narrow white region around the borders between the borders and the black background"?

**Comment by Boarders** [comment] 2021-11-22 05:28
Thanks for the tips, super helpful as I am not yet familiar with the library. The part I am still confused about is how I would render the entire background, outside of the border boxes with one colour? You might already have said so and I am just confused.

**Comment by jtdaugherty** [comment] 2021-11-22 05:30
I'm not sure I understand. In your screenshot, I don't know what you mean by "outside of the border boxes." When I look at that image, the area that fits that description to me is the area that is already black. So maybe you mean something else?

**Comment by jtdaugherty** [comment] 2021-11-22 05:34
Oh, I think I see the problem. You have:
```haskell
borderWithLabel (withAttr "title" $ txt "To do") $
withAttr "to-do-list" $
```
That means that everything inside the border will have the `to-do-list` attribute, but by using `withAttr` you get an attribute that is not *merged* with the global default. You are saying "use exactly this attribute, and if it doesn't specify a background color, use the terminal background color." Instead, I think `withDefAttr` there would give you the result you want (merge the foreground color of `to-do-list` with the background color of the global default).

**Comment by jtdaugherty** [comment] 2021-11-22 05:35
Strangely, I read my own docs and they disagreed with what I just said. I'll investigate.

**Comment by Boarders** [comment] 2021-11-22 05:36
Ah thanks, let me give that a try. Sorry if I was unclear, I just meant that I would like everything outside of the box containing the date to be the background colour.

**Comment by jtdaugherty** [comment] 2021-11-22 05:38
Gotcha. I just confirmed that the code actually *should* do attribute merging even with `withAttr`. I'll have to think more about why that would make any difference. But in the mean time, yeah, you can try `withDefAttr`.

**Comment by Boarders** [comment] 2021-11-22 05:42
Thanks very much, you have been more than helpful and I'm really enjoying using your library.

**Comment by jtdaugherty** [comment] 2021-11-22 05:44
I'm glad to hear it! I cloned and built `task` and just changed `backgroundCol` and everything seemed to change as desired. (And that's without changing `withAttr`.) Is there a more specific test I could do? Or pull a patch of yours and see if I can get it working?

**Comment by jtdaugherty** [comment] 2021-11-22 05:45
(Also, this would be a bigger, change, but: editing tasks seems to have some behavioral issues and you might consider using the built-in Brick line editor when rendering tasks in the editing state. That takes care of a lot of stuff for you.)

**Comment by jtdaugherty** [comment] 2021-11-22 05:46
(I'm building `a40934`.)

**Comment by jtdaugherty** [comment] 2021-11-22 05:46
Here's the editor I was referring to:

https://hackage.haskell.org/package/brick-0.65/docs/Brick-Widgets-Edit.html

**Comment by jtdaugherty** [comment] 2021-11-22 05:54
With some hacking, I got this result which looks close to what you want (but the border around the box doesn't have a white background yet)
<img width="874" alt="Screen Shot 2021-11-21 at 9 53 40 PM" src="https://user-images.githubusercontent.com/427221/142807907-e88270c3-0866-48e9-bd29-b4fe7f0beb56.png">
:

**Comment by jtdaugherty** [comment] 2021-11-22 05:54
Here's the diff:
```diff
diff --git a/app/Main.hs b/app/Main.hs
index af855e1..b21e850 100755
--- a/app/Main.hs
+++ b/app/Main.hs
@@ -203,16 +203,14 @@ draw date (ViewState tasks mode) =
   let
     header, textWindow :: TaskWidget
     header =
-      visible $
       withAttr "header" $
-      vLimitPercent 5 $
 --      borderWithLabel emptyWidget $
 --      viewport "header"  Both $
 --      setAvailableSize (100, 100) $
-      center $   
+      hCenter $
+      withDefAttr "subtitleBox" $
       border $
 --      padAll 1 $
-      visible $
       withAttr "subtitle" $
       txt (renderDate $ date)
     textWindow =
@@ -282,16 +280,15 @@ drawNextTasks = foldr (\t w -> drawTask t <=> w) emptyWidget
 edAttrMap :: AttrMap
 edAttrMap =
   attrMap globalDefault
-    [ ("title"   , titleCol    `on` backgroundCol)
-    , ("subtitle", subtitleCol `on` backgroundCol)
-    , ("text"    , textCol     `on` backgroundCol)
-    , ("to-do-list", textCol   `on` backgroundCol)
-    , ("highlighted", textCol  `on` highlightCol)
-    , (borderAttr, textCol     `on` borderCol)
+    [ ("title"   ,    fg titleCol)
+    , ("subtitle",    fg subtitleCol)
+    , ("subtitleBox", bg Vty.white)
+    , ("highlighted", bg highlightCol)
+    , (borderAttr,    bg borderCol)
     ]
 
 globalDefault :: Attr
-globalDefault = textCol `on` backgroundCol
+globalDefault = textCol `on` Vty.black
 
 -- colour scheme
 type Colour = Color
@@ -300,7 +297,7 @@ textCol :: Colour
 textCol = richBlack
 
 backgroundCol :: Color
-backgroundCol = babyPowder
+backgroundCol = black -- babyPowder
 
 headerBackground :: Color
 headerBackground = lightPurple
```

**Comment by jtdaugherty** [comment] 2021-11-22 05:54
I should also mention that the call to `center` was replaced with `hCenter` which allowed me to get rid of the `vLimitPercent`.

**Comment by Boarders** [comment] 2021-11-22 05:55
Thanks, I am still building out the functionality for task editing but I would rather control it myself. I tried out the built-in widget but found it would be easier in the end to roll my own as there are certain features that I would like. I'll try messing with the `withDefAttr` to see if it has the behaviour I would like and get back to you! Thanks again!

**Comment by jtdaugherty** [comment] 2021-11-22 05:57
Here's another version that seems to be what you want, I think
<img width="876" alt="Screen Shot 2021-11-21 at 9 56 46 PM" src="https://user-images.githubusercontent.com/427221/142808193-874eba05-c263-4d6d-85d4-1783f7066f33.png">
:

**Comment by jtdaugherty** [comment] 2021-11-22 05:57
The key with that version was introducing an attribute override for `borderAttr`:
```diff
diff --git a/app/Main.hs b/app/Main.hs
index af855e1..3edd1c7 100755
--- a/app/Main.hs
+++ b/app/Main.hs
@@ -203,16 +203,15 @@ draw date (ViewState tasks mode) =
   let
     header, textWindow :: TaskWidget
     header =
-      visible $
       withAttr "header" $
-      vLimitPercent 5 $
 --      borderWithLabel emptyWidget $
 --      viewport "header"  Both $
 --      setAvailableSize (100, 100) $
-      center $   
+      hCenter $
+      withDefAttr "subtitleBox" $
+      overrideAttr borderAttr "subtitleBorder" $
       border $
 --      padAll 1 $
-      visible $
       withAttr "subtitle" $
       txt (renderDate $ date)
     textWindow =
@@ -282,16 +281,16 @@ drawNextTasks = foldr (\t w -> drawTask t <=> w) emptyWidget
 edAttrMap :: AttrMap
 edAttrMap =
   attrMap globalDefault
-    [ ("title"   , titleCol    `on` backgroundCol)
-    , ("subtitle", subtitleCol `on` backgroundCol)
-    , ("text"    , textCol     `on` backgroundCol)
-    , ("to-do-list", textCol   `on` backgroundCol)
-    , ("highlighted", textCol  `on` highlightCol)
-    , (borderAttr, textCol     `on` borderCol)
+    [ ("title"   ,    fg titleCol)
+    , ("subtitle",    fg subtitleCol)
+    , ("subtitleBox", bg Vty.white)
+    , ("highlighted", bg highlightCol)
+    , (borderAttr,    bg borderCol)
+    , ("subtitleBorder", bg Vty.white)
     ]
 ```

**Comment by jtdaugherty** [comment] 2021-11-22 05:59
The latest version works by making it so that when `borderAttr` is consulted for the subtitle box, the value of `subtitleBorder` is used instead, making sure that that particular border has a white background.

**Comment by Boarders** [comment] 2021-11-22 15:56
Thanks! I don't think I was very clear, basically I want a layout where inside the box with the date and with checklist the background is white and outside of those regions the background is another colour, I'm still not yet sure if brick offers such a functionality.

**Comment by jtdaugherty** [comment] 2021-11-22 16:13
Unfortunately, that isn't possible because of how border-drawing works: the border characters are [line-drawing characters](https://www.compart.com/en/unicode/U+007C), and the terminal draws them with a background color on both sides of the border. Brick doesn't have any control over that. However, you *could* choose different border characters by using your own custom border style. If you could find border characters that were drawn on the outside edges rather than the middles of the character cells, you could get the effect you're looking for. The other way to get the effect you're describing would be to use no borders at all, but just use background color changes to delineate the elements of your UI.

**Comment by jtdaugherty** [comment] 2021-11-22 16:14
For reference, if you're interested in finding alternative line-drawing characters, there's this:

https://en.wikipedia.org/wiki/Box-drawing_character

But bear in mind that the vast majority of those will suffer from this problem.

**Comment by Boarders** [comment] 2021-11-22 16:16
Thanks, that is very helpful!

**Comment by jtdaugherty** [comment] 2021-11-22 16:50
Okay, you're welcome. Please let me know if there's anything else you'd like to discuss here, or close the ticket if not. Thanks!

**Closed** 2021-11-22 16:53 UTC
