### ISSUE TITLE
Performance issues with mouse events

### ISSUE THREAD

**Issue by goodsoft** [jtdaugherty/brick#178] opened 2018-05-21 19:45 UTC
I have several clickable viewports in my app.
When I press a mouse button and start moving cursor around, the app event loop gets flooded with `MouseDown` events.

It wouldn't be a problem if events were processed faster than they arrive, but each event processing takes too long, so the event loop gets clogged and events continue to arrive for some time after I unpress mouse button.

I tried to investigate the reason for this lag and found that my `appHandleEvent` takes on average 0.05-0.10ms, while the interval between `appHandleEvent` calls (i.e. framework overhead) is 10-15ms, which is clearly larger than mouse event rate.
That means, the problem is in the framework or underlying terminal library.

I'll still try to build my app with profiling enabled and investigate further, but some info on whether this is a known issue and what could be a source of the problem would help a lot, thanks.

**Comment by goodsoft** [comment] 2018-05-21 20:02
After posting the issue I remembered that rendering happens outside of event handling, so I added `cached` to every widget with dynamic content and commented out all `invalidateCacheEntry` calls to test if the problem is with my rendering callbacks.

That didn't help, the gap betwee events is still 10-15ms.

**Comment by jtdaugherty** [comment] 2018-05-21 20:08
Assuming your event handler timings are right (and that can be tricky to get right in Haskell due to laziness), the biggest factor will be rendering cost, which will be determined by interface complexity. Even in the presence of `cached` calls, the underlying `vty` library does an image diff on every redraw. Even if the redraw results in no screen changes, the diff computation can be costly and depends on the structure of the vty `Image`s being diffed, which depend on your interface layout, Brick combinators used, etc.

Is this application available publicly? If so, I could take a look.

**Comment by goodsoft** [comment] 2018-05-21 20:12
It's not yet publicly available, and I can't share it due to NDA.
Still, good point about laziness, I'll try to redo timings while forcing strictness everywhere and see if it changes anything.

**Comment by jtdaugherty** [comment] 2018-05-21 20:15
Another way to determine whether this really is a rendering issue is to do something like
* on `MouseDown` event, stick the event in your state
* replace your top-level rendering function with one that just returns `[txt $ show $ eventField myState]`

If that can't keep up, then that's definitely interesting.

**Comment by jtdaugherty** [comment] 2018-05-21 20:19
As a data point at suggesting that what you're doing should be possible, the program [tart](https://github.com/jtdaugherty/tart) is heavily mouse-driven and is able to deal with mouse dragging without too much trouble. That program does have difficulty for very large terminal sizes or image sizes where the drawing cost is high, though, so there *is* a limit to this (but, then again, nobody should be using a terminal window quite that huge anyway).

**Comment by goodsoft** [comment] 2018-05-21 20:25
I tried your test, and it works without lag.
So it's definitely not an event loop problem, but rather something in rendering or event handling.

Thank you for your help!

**Comment by jtdaugherty** [comment] 2018-05-21 20:30
You're welcome! I should point out that the problem could still be that a Vty or Brick operation is costly enough that it's adding up in your case, so this doesn't necessarily mean there isn't some performance issue there, in terms of your UI. So if you determine that this is a library issue rather than an application issue, a minimal demo program that surfaces the performance hotspot would be very useful if you still can't release your program. Thanks!

**Comment by goodsoft** [comment] 2018-05-21 20:50
Okay, I tried testing my widgets' performance one-by-one, so I started with "background" widget which just fills the screen with default attribute — `fill ' '`
Basically, my rendering function is `[txt $ show $ eventField state, fill ' ', viewport VName Both emptyWidget]` (viewport is for click event registration).
If you move mouse over this configuration for some time, events begin accumulate in the queue.

**Comment by jtdaugherty** [comment] 2018-05-21 21:07
Is this a list of layers?

**Comment by jtdaugherty** [comment] 2018-05-21 21:29
For what it's worth, the `fill ' '` above will just cover up the `viewport VName Both emptyWidget`. I imagine that was just pseudocode for your real UI, though. If you do nothing but render the viewport, do you still have the same problem?

**Comment by goodsoft** [comment] 2018-05-21 21:39
It's not pseudocode, it's `appDraw` almost verbatim (except for qualified import prefix and viewport name).
The viewport is there for click registration, as just `fill ' '` won't report its extent and generate Brick `MouseDown` event.

I'll try comparing `viewport VName Both $ fill ' '` vs `viewport VName Both emptyWidget` now.

**Comment by jtdaugherty** [comment] 2018-05-21 21:48
`viewport VName Both $ fill ' '` is illegal, as you'll soon find out, since viewports require that their child widgets are fixed-side in the scrolling direction.

**Comment by jtdaugherty** [comment] 2018-05-21 21:49
Also, `viewport VName Both emptyWidget` shouldn't report any extent anyway, or if it does, it'll be a zero-width, zero-height extent that should never match any mouse events. Is that not what is happening?

**Comment by goodsoft** [comment] 2018-05-21 22:11
Without `viewport VName Both emptyWidget` I don't get any mouse events, with it I get mouse events for every point on the screen.
I reported related issue as #175. Basically, `viewport` creates a filler image for the entire available space, while `clickable` does not.

**Comment by jtdaugherty** [comment] 2018-05-21 22:17
Ah, okay, thanks - I forgot about that behavior. In that case it sounds like this could just reduce to a single layer, `[viewport VName Both emptyWidget]` - presumably that alone is sufficient to exhibit the bad performance?

**Comment by jtdaugherty** [comment] 2018-05-21 22:47
To test, I modified `MouseDemo.hs` from the Brick demo programs directory to add a new (bottom-most) layer of `viewport Background Both emptyWidget`. Even for very large terminal sizes, on my machine, the performance was very good; if there was a delay in event queue processing, it was probably under 100ms. So I'm not sure what to make of this.

**Comment by goodsoft** [comment] 2018-05-21 23:10
No, the following code didn't have lag:
```[txt $ show $ eventField state, viewport VName Both emptyWidget]```
The following code, on the contrary, did:
```[txt $ show $ eventField state, fill ' ', viewport VName Both emptyWidget]```

I'll try a bit cleaner test with a stopwatch later tonight or tomorrow, depending on when a certain resource-consuming task on my PC will be complete.

**Comment by goodsoft** [comment] 2018-05-21 23:28
Okay, I tried reproducing this again and didn't have a lag with any configuration above, as well.
Either way, I'll continue investigating tomorrow and will let you know if I have any results.

**Comment by jtdaugherty** [comment] 2018-05-21 23:31
Okay. Thanks!

**Comment by goodsoft** [comment] 2018-05-22 17:29
I got back to investigating and tried to run `brick-mouse-demo` for a change.
I found that if you try quickly moving mouse over the three buttons left-right for some time, events begin to pile up and the app consumes 100+% of CPU.
The effect is even more apparent if you do it for some time.
For the record, my terminal size is 130x94 in this case.

**Comment by jtdaugherty** [comment] 2018-05-25 14:36
Even at that size, I can't reproduce that behavior; it's possible the machine I'm doing this on is just faster than yours enough to avoid the pileup. Another thing I'm wondering is, what platform is this on, and which terminal emulator are you using?

**Comment by goodsoft** [comment] 2018-05-25 14:42
```Linux 4.16.9-1-ARCH #1 SMP PREEMPT Thu May 17 02:10:09 UTC 2018 x86_64 GNU/Linux```
Late-2012 Mac Mini with Intel i5-3210M and 16 GB of RAM
Terminal emulator — Konsole

Don't you see CPU usage spikes when you move mouse fast enough?

**Comment by jtdaugherty** [comment] 2018-05-25 16:11
On my Macbook Pro (3.1 GHz Intel Core i7) I see about 60% peak CPU usage in the application and 20% CPU usage from the terminal emulator (iTerm2), but never more than that regardless of mouse activity and the program never gets behind.

**Comment by jtdaugherty** [comment] 2018-05-25 16:11
With that said, that's enough of a hardware difference that I am not too surprised that 60% for me is 100% for you.

**Comment by jtdaugherty** [comment] 2019-06-12 17:54
I'm going to close this. It's been open for a year and it isn't clear what a good next step is. If this becomes a show-stopping problem, please feel free to re-open.

**Closed by jtdaugherty** 2019-06-12 17:54 UTC
