### ISSUE TITLE
inconsistent scroll position after listMoveTo

### ISSUE THREAD

**Issue by simonmichael** [jtdaugherty/brick#11] opened 2015-08-20 11:51 UTC
On a particular screen, the items are ordered by date, so on entering it I move the selection to the last (most recent) item:
```
initRegisterScreen d args st@AppState{aopts=opts, ajournal=j, aScreen=s@RegisterScreen{}} =
  st{aScreen=s{rsState=is'}}
  where
    is' =
      listMoveTo (length items) $
      list (Name "register") (V.fromList items) 1
    items = ...
```
Sometimes the selected item appears at the bottom of the screen; sometimes it appears at the top (and I have to scroll up to see that there are older items). I'm not sure what controls this.

In this situation I think I'd like it to scroll down from the top just enough to reveal the selected item at the bottom of the screen.

Ideally I suppose there would be API to control List's scroll state (maybe it can expose a ViewportScroll ?)

**Comment by jtdaugherty** [comment] 2015-08-20 15:30
I'll look into this. The thing about scrolling is that it isn't in the widget state at all; it's in the renderer (for reasons that I can go into).  So you can get at that information, but only in event handlers.  The only state related to scrolling that *is* stored in the List is the list selection index.  Then when the list is rendered, that selection index is used to tell the renderer which element in the list should be scrolled to, and the scrolling state is managed by the renderer after that.

I'm curious: when you see this difference in behavior in `listMoveTo`, is there also a difference in the number of list items?  And is the number of list items less than the height of the screen?

**Comment by jtdaugherty** [comment] 2015-08-20 15:54
After doing some testing of my own I can't reproduce this, so any details on your situation would be especially helpful.

**Comment by jtdaugherty** [comment] 2015-08-20 15:56
I'm also curious about when in the program this occurs: do you repopulate the list occasionally?

**Comment by simonmichael** [comment] 2015-08-20 18:54
I populate the list each time the user enters this screen, and move the selection to the end immediately after that. On entering the screen, sometimes the selected item is at the bottom of the terminal, and sometimes it's at the top (it's the only line showing). It happens both with more and less elements than fit on the screen, and it varies somewhat on successive runs of the program and even successive entries to the screen during the same run (with no data changes).

I have since flipped the sort order, so currently I start at the top and this is affecting me less.

**Comment by jtdaugherty** [comment] 2015-08-20 22:06
In that case, the reason for the behavior you are seeing is almost certainly that the old scrolling state of the list's viewport is affecting the scrolling behavior you get when you call `listMoveTo`.  You are reinitializing the list but the old viewport state (its vertical offset) is not being reset to zero, so scrolling changes triggered by `listMoveTo` are not going to behave consistently.  I think the solution is to add functions to `EventM` that allow you to reset a viewport, but I'll have to think about whether that's the best approach.

**Comment by jtdaugherty** [comment] 2015-08-22 03:31
Assuming my theory above is correct, you can get the behavior you want by pulling the latest commits and then, in your event handler, where you repopulate your list, also do this:
```
vScrollToBeginning $ viewportScroll (listName someList)
```

**Comment by jtdaugherty** [comment] 2015-08-22 03:31
This updates the viewport state (same as hitting `Home`, essentially) so that when the list is re-drawn, the item you moved to is at the bottom of the screen.

**Comment by simonmichael** [comment] 2015-08-23 01:08
> On Aug 21, 2015, at 8:31 PM, Jonathan Daugherty <notifications@github.com> wrote:
> This updates the viewport state (same as hitting Home, essentially) so that when the list is re-drawn, the item you moved to is at the bottom of the screen.
> 

Thanks! That seems to be working well.

**Comment by jtdaugherty** [comment] 2015-08-23 02:56
If this is working as desired, please close this issue (or let me know what else I can do).

**Closed** 2015-08-23 03:51 UTC
