### ISSUE TITLE
row ... now exceeds region width

### ISSUE THREAD

**Issue by deliciouslytyped** [jtdaugherty/brick#471] opened 2023-06-16 20:42 UTC
With `nix-shell -I nixpkgs=channel:nixos-unstable -p "ghc.withPackages (p: [ p.brick p.strip-ansi-escape ])"`
and the following code, based on https://stackoverflow.com/questions/63662243/rgb-terminal-colors-with-haskell-and-brick#comment112661541_63675718 , I'm getting the attached error, and I can't tell why. My terminal should have enough space to render 40 columns.

```
import Data.Complex
import Brick
import Graphics.Vty as V
import Graphics.Vty.Image.Internal (Image (HorizText))
import Control.Monad
import Data.Text (pack, unpack)
import qualified Data.Text.Lazy as L
import Data.String.AnsiEscapeCodes.Strip.Text (stripAnsiEscapeCodes)
import Debug.Trace

mandelbrot w zoom a b =
  let
    halfw = w / 2
    trf v = ( v - halfw ) / zoom
    lim = 100

    reset = "\x1b[0m"
    bgColorSignal = "\x1b[48;2"

    sample x y = iter 0 (0 :+ 0) $ (trf $ x + a) :+ (trf $ y + b)

    iter cnt acc pos
      | (magnitude acc >= 2) = " "
      | (cnt == lim) =
        let
          colorF v = floor $ cnt * ( abs $ (phase acc) / pi - 1 + v )
          colors = join $ fmap (\v -> ";" ++ (show $ colorF v)) [0, 1.2, 2.4]
        in
          bgColorSignal ++ colors ++ "m " ++ reset
      | otherwise = iter (cnt + 1) (acc^2 + pos) pos

  in
    [ join [ sample x y | x <- [0..w-1] ] | y <- [0..w-1]]

data MyState a = MyState { _x :: a, _y :: a, _zoom :: a } deriving Show
interactive =
  let
    stripEscapes = unpack . stripAnsiEscapeCodes . pack
    width = 20
    draw = \st -> [raw $ vertCat $ fmap (\str -> HorizText V.defAttr (L.pack str) ((\x -> trace ("\x1b[?1049l" ++ (show x) ++ "\x1b[?1049h") x) $ fromIntegral $ L.length $ L.pack $ stripEscapes str) 1) $ mandelbr>
    handleEvent (VtyEvent (V.EvKey (V.KChar 'q') [])) = halt
    handleEvent (VtyEvent (V.EvKey V.KRight [])) = modify $ \s -> MyState { _x = (_x s) + 5, _y = _y s, _zoom = _zoom s }
    handleEvent (VtyEvent (V.EvKey V.KLeft [])) = modify $ \s -> MyState { _x = (_x s) - 5, _y = _y s, _zoom = _zoom s }
    handleEvent (VtyEvent (V.EvKey V.KDown [])) = modify $ \s -> MyState { _x = _x s, _y = (_y s) + 5, _zoom = _zoom s }
    handleEvent (VtyEvent (V.EvKey V.KUp [])) = modify $ \s -> MyState { _x = _x s, _y = (_y s) - 5, _zoom = _zoom s }
    handleEvent (VtyEvent (V.EvKey (V.KChar '-') [])) = modify $ \s -> MyState { _x = _x s, _y = _y s, _zoom = (_zoom s) - 5 }
    handleEvent (VtyEvent (V.EvKey (V.KChar '+') [])) = modify $ \s -> MyState { _x = _x s, _y = _y s, _zoom = (_zoom s) + 5 }

    initState = MyState { _x = 0, _y = 0, _zoom = 20 }

    app :: App (MyState Double) e ()
    app = App { appDraw = draw, appChooseCursor = neverShowCursor, appHandleEvent = handleEvent, appStartEvent = pure (), appAttrMap = const (attrMap V.defAttr []) }
  in
    defaultMain app initState
```

```
ghci> :load mandel.hs
[1 of 1] Compiling Main             ( mandel.hs, interpreted )
Ok, one module loaded.
ghci> interactive
2020202020202020202020202020202020202020*** Exception: row 0 now exceeds region width
CallStack (from HasCallStack):
  error, called at src/Graphics/Vty/PictureToSpans.hs:347:16 in vty-5.37-DdQWc79tNXWJpSkxmXck6C:Graphics.Vty.PictureToSpans
```

**Comment by deliciouslytyped** [comment] 2023-06-16 21:29
I guess with the way this works currently you just can't do this. I tried making the sizes in the vty fields the appropriate size of (or larger than) the string and that seems to at least not crash, but there are bad rendering bugs and I don't know why.

**Comment by deliciouslytyped** [comment] 2023-06-16 22:16
The rendering bugs are probably caused by brick not redrawing the entire string.

**Comment by jtdaugherty** [comment] 2023-06-17 00:16
Hi @deliciouslytyped - it's a bit hard for me to tell what the expected behavior of the program is, but I can say this: if the escape-stripping routine somehow misses some, that will result in a broken layout. I don't know exactly what you'd need to do to trigger that exception (which is from `vty`, not `brick`), but I suspect that using the Vty and Brick APIs to build images rather than going from escape sequences to text and back might give more stable results.

**Comment by deliciouslytyped** [comment] 2023-06-17 00:48
Yeah, sorry for the mess.
I think I _was_ building images?

In any case for the moment I ended up writing my own crappy event loop without brick, and when I have more time I will try to come back to this.

**Comment by jtdaugherty** [comment] 2023-06-17 00:53
> I think I was building images?

Ultimately the code does build a bunch but it does so using an Image constructor directly (`HorizText`) rather than using the image constructor API (e.g. with [string](https://hackage.haskell.org/package/vty-5.38/docs/Graphics-Vty-Image.html#v:string)). But it also does this in a roundabout way, and I actually can't tell how you manage to get any attributes into the final result. A more direct approach would be to skip the process of generating and then stripping ANSI escapes and using Vty's color constructors instead. (It supports higher-resolution colors, so that shouldn't be an obstacle.)

> The error seems to perhaps happen if the reported string size (which one is what?) is smaller than the size of the data in the string.

I don't know what this is referring to, but this is one of the things that would be avoided by using the Brick or Vty APIs directly, I think.

**Comment by jtdaugherty** [comment] 2023-06-22 19:54
@deliciouslytyped do you have what you need, now? Or is there something else we can discuss here?

**Comment by deliciouslytyped** [comment] 2023-06-22 22:40
I won't have time to work on this for at least another two weeks.

**Comment by jtdaugherty** [comment] 2023-12-17 00:51
It's been a few months since this was active, so I'm going to close it - but if this becomes an active area of work again and you need help, please re-open (or open a new issue). Thanks!

**Closed by jtdaugherty** 2023-12-17 00:51 UTC
