### ISSUE TITLE
Border Styling seems wrong

### ISSUE THREAD

**Issue by NorfairKing** [jtdaugherty/brick#197] opened 2018-11-15 19:33 UTC
This code:

```
drawCard :: Card -> Widget n
drawCard c@(Card suit _) =
    border $ withAttr (suitAttr suit) $ str $ prettyCard c
```

and this code as well:

```
drawCard :: Card -> Widget n
drawCard c@(Card suit _) =
    withAttr (suitAttr suit) $ border $ str $ prettyCard c
```

produces this output:

![out](https://user-images.githubusercontent.com/3521180/48576746-9ea50500-e915-11e8-9841-813fe2b36117.png)

They both seem wrong. The first version should not style any part of the border, the second version should style the entire border. And neither should style the border of another widget.

**Comment by jtdaugherty** [comment] 2018-11-15 20:13
Can you provide the code for `prettyCard`? In particular, to reproduce I need the suit characters you're using in the cards.

**Comment by jtdaugherty** [comment] 2018-11-15 20:29
Yes, thanks! What terminal emulator are you using in the screenshot above?

**Comment by NorfairKing** [comment] 2018-11-15 20:30
The above is `urxvt`.

The same happens in xterm though:
![xterm](https://user-images.githubusercontent.com/3521180/48579772-b54f5a00-e91d-11e8-972b-e6d7bd82883b.png)

**Comment by jtdaugherty** [comment] 2018-11-15 20:32
Interesting. I can't reproduce in either `Terminal.app` or `iTerm2`. Does the behavior persist if you use a different character in place of the suit characters such as `'x'`?

**Comment by jtdaugherty** [comment] 2018-11-15 20:33
For what it's worth, there are two misbehaviors here. One is the run-on attribute in the first example, and although the second example also has that problem, the other problem you mentioned (not coloring the border, too) is actually because you're using `withAttr` instead of `withDefAttr`.

**Comment by jtdaugherty** [comment] 2018-11-15 20:33
(Or `forceAttr`, for that matter.)

**Comment by NorfairKing** [comment] 2018-11-15 20:34
Yes, the same happens with other chars:

![xterm](https://user-images.githubusercontent.com/3521180/48579995-3b6ba080-e91e-11e8-839d-92b58a3b8cab.png)
![urxvt](https://user-images.githubusercontent.com/3521180/48580000-3d356400-e91e-11e8-9b1c-4d6c6ee16786.png)

**Comment by NorfairKing** [comment] 2018-11-15 20:36
`withDefAttr` seems to fix things: 
![withdefattr](https://user-images.githubusercontent.com/3521180/48580072-74a41080-e91e-11e8-88f5-65969ea1f6cc.png)

**Comment by jtdaugherty** [comment] 2018-11-15 20:36
What version of `vty` are you using?

**Comment by NorfairKing** [comment] 2018-11-15 20:38
`vty-5.21` in `lts-12.18`

**Comment by jtdaugherty** [comment] 2018-11-15 20:43
W.r.t. `withAttr`, it's a little bit of a wart in the API that this is the actual behavior. In practice I almost never use `withAttr` because of it, but it has its uses. From the Haddock:
```
Note that the widget may use further calls to withAttr to override this; if you really
want to prevent that, use forceAttr. Attributes used this way still get merged
hierarchically and still fall back to the attribute map's default attribute. If you want
to change the default attribute, use withDefAttr.
```
So in your case the `border` uses `setAttr`, and that takes precedence over your use of it. But if you use `withDefAttr`, that causes the (missing) border attribute to automatically get merged with the default, thus getting the coloring you wanted.

As for `vty`, that's too bad; I don't think anything in later releases is related to this behavior, so upgrading probably won't help. Attribute run-ons like the one you are seeing are usually due to a bug in the underling attribute state management in `vty`, so I don't think the run-ons themselves are a `brick` issue. Would you be willing to write a minimal demo program that reproduces this misbehavior for you and create a ticket with it on the `vty` repo?

**Comment by jtdaugherty** [comment] 2018-11-15 23:42
Since this isn't a `brick` problem and since we've resolved one of the issues raised here, I'm going to close this - but let's please continue this on the `vty` repository if there is an attribute run-on problem that can be reproduced there. Thanks for reporting this!

**Closed by jtdaugherty** 2018-11-15 23:42 UTC
